// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWYabiDdi8aGB5tUVc_yLj5U_6HqS9S8',
    appId: '1:727412711240:android:84ffa0839823ab33ad9d7d',
    messagingSenderId: '727412711240',
    projectId: 'class-729-app',
    storageBucket: 'class-729-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV8M8v1ATr4Cz5oGyt-pXWQI_j1diYfyU',
    appId: '1:727412711240:ios:939ccfb5846e4112ad9d7d',
    messagingSenderId: '727412711240',
    projectId: 'class-729-app',
    storageBucket: 'class-729-app.firebasestorage.app',
    iosBundleId: 'com.class729.class729',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeHqORn_KuacRa6p4mPnD-IgZhjpi0occ',
    appId: '1:727412711240:web:22799cd69e896e1ead9d7d',
    messagingSenderId: '727412711240',
    projectId: 'class-729-app',
    authDomain: 'class-729-app.firebaseapp.com',
    storageBucket: 'class-729-app.firebasestorage.app',
    measurementId: 'G-L1LB1LWPHG',
  );
}
